import type { Metadata } from 'next';
import { Noto_Sans, Noto_Sans_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Noto_Sans({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Noto_Sans_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative h-full antialiased bg-neutral-900 text-neutral-100`}
      >
        <main className="flex flex-col min-h-screen relative font-sans">
          <div className="grow flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
